name: Deploy my-desk-front

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16.15.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_HOST: ${{ secrets.NEXT_PUBLIC_API_HOST }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Make zip file for archive
        run: |
          zip -qq -r before-deploy.zip package.json package-lock.json node_modules/ .next/ public/ Dockerfile
          mv before-deploy.zip deploy/$GITHUB_SHA.zip

      - name: configure aws credientials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload zip file to s3
        run: aws s3 cp --region ap-northeast-2 deploy/$GITHUB_SHA.zip s3://mydesk-front-archive/$GITHUB_SHA.zip

      - name: Trigger aws codedeploy
        run: >
          aws deploy create-deployment
          --application-name mydesk-front
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name mydesk-front-master-group
          --s3-location bucket=mydesk-front-archive,key=$GITHUB_SHA.zip,bundleType=zip
